# Generated by Django 3.2.12 on 2023-11-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=1, unique=True),
        ),
    ]
