# Generated by Django 3.2.12 on 2023-11-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20231115_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='label',
            field=models.CharField(default='*', max_length=1),
        ),
    ]
